spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academate_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: kerimlifatime417@gmail.com
    password: dkyiswspxzfqghnx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  s3:
    region: fra1
    bucket: profile-image
    access-key: DO00RCU24W7QDDJ77V74
    secret-key: MFNb1slRvHA+sG53X4qz6buzzybHslNzlvKdXO67cpE
    endpoint: https://fra1.digitaloceanspaces.com

  google:
    client-id: 966605955984-a2536djlra7n2vnf4u4codsk2kothdhv.apps.googleusercontent.com
    client-secret: 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
    refresh-token: "1//04wczR9a5cxi3CgYIARAAGAQSNwF-L9IrQtziuMDXbXZ5opuxlDZfcQZFoTiuIU-qimVuBZOPjVBYh0CJi157Sd_M7mmu2PDR7Bk"
    calendar-id: primary

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
