spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    root: WARN
    com.example.academatebackend: INFO
    org.springframework.security: WARN
