spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academate_dev
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: kerimlifatime417@gmail.com
    password: dkyiswspxzfqghnx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  s3:
    region: fra1
    bucket-name: profile-image
    access-key: DO00RCU24W7QDDJ77V74
    secret-key: MFNb1slRvHA+sG53X4qz6buzzybHslNzlvKdXO67cpE
    endpoint: https://fra1.digitaloceanspaces.com

  zoom:
    account-id: KE1FzARKTjufHiuURlqGNQ
    client-id: QfKsunLDRBa_gZja2Va1A
    client-secret: ZdWdGjYeBtUp94qj1qT0tiLnJtRpDcLK

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.orm.jdbc.extract: OFF
