package com.example.academatebackend.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    LOGOUT_ALL,
    REGISTER,
    EMAIL_VERIFIED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    ROLE_CHANGED,
    USER_DEACTIVATED,
    TEACHER_VERIFIED,
    PARENT_LINKED,
    PARENT_LINK_VERIFIED,
    LESSON_BOOKED,
    LESSON_CONFIRMED,
    LESSON_CANCELLED,
    LESSON_COMPLETED,
    REVIEW_CREATED
}
